---
abstract: 'Bash completion routines for function & function argument over Riap'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  File::Which: 0
  File::chdir: 0
  Module::Build: 0.3601
  Perinci::Access: 0
  Perinci::Examples: 0.08
  Test::More: 0.88
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-BashComplete
requires:
  List::MoreUtils: 0
  Log::Any: 0
  Perinci::Sub::GetArgs::Argv: 0.13
  Rinci: v1.1.10
  UUID::Random: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Perinci-BashComplete/
  repository: http://github.com/sharyanto/perl-Perinci-BashComplete
version: 0.31
